# ==============================================================================
# Shelterluv to Fi Nano Breed Translation Dictionary Module
# ==============================================================================

BREED_MAP = {
    # --- Exact / Normalized Matches ---
    "Affenpinscher": "Affenpinscher",
    "Akbash": "Akbash Dog",
    "Akita": "Akita",
    "Basenji": "Basenji",
    "Beagle": "Beagle",
    "Beauceron": "Beauceron",
    "Berger Picard": "Berger Picard",
    "Bernese Mountain Dog": "Bernese Mountain Dog",
    "Bichon Frise": "Bichon Frise",
    "Black Mouth Cur": "Black Mouth Cur",
    "Bloodhound": "Bloodhound",
    "Blue Lacy": "Blue Lacy",
    "Boerboel": "Boerboel",
    "Bolognese": "Bolognese",
    "Borzoi": "Borzoi",
    "Boxer": "Boxer",
    "Briard": "Briard",
    "Bulldog": "Bulldog",
    "Bullmastiff": "Bullmastiff",
    "Canaan Dog": "Canaan Dog",
    "Carolina Dog": "Carolina Dog",
    "Catahoula Leopard Dog": "Catahoula Leopard Dog",
    "Chihuahua": "Chihuahua",
    "Chow Chow": "Chow Chow",
    "Cockapoo": "Cockapoo",
    "Collie": "Collie",
    "Coonhound": "Black and Tan Coonhound",  # General fallback
    "Dachshund": "Dachshund",
    "Dalmatian": "Dalmatian",
    "Dogo Argentino": "Dogo Argentino",
    "Dogue de Bordeaux": "Dogue de Bordeaux",
    "Entlebucher": "Entlebucher Mountain Dog",
    "Eskimo Dog": "Canadian Eskimo Dog",
    "Feist": "Feist",
    "Great Dane": "Great Dane",
    "Greater Swiss Mountain Dog": "Greater Swiss Mountain Dog",
    "Greyhound": "Greyhound",
    "Havanese": "Havanese",
    "Keeshond": "Keeshond",
    "Komondor": "Komondor",
    "Kuvasz": "Kuvasz",
    "Leonberger": "Leonberger",
    "Lhasa Apso": "Lhasa Apso",
    "Lowchen": "Löwchen",
    "Maltese": "Maltese",
    "Mastiff": "Mastiff",
    "Mountain Cur": "Mountain Cur",
    "Newfoundland": "Newfoundland",
    "Norbottenspets": "Norrbottenspets",
    "Otterhound": "Otterhound",
    "Papillon": "Papillon",
    "Pekingese": "Pekingese",
    "Pomeranian": "Pomeranian",
    "Poodle": "Poodle",
    "Pug": "Pug",
    "Puli": "Puli",
    "Retriever": "Labrador Retriever",  # Base fallback
    "Rottweiler": "Rottweiler",
    "Saint Bernard": "Saint Bernard",
    "Saluki": "Saluki",
    "Samoyed": "Samoyed",
    "Schipperke": "Schipperke",
    "Schnauzer": "Standard Schnauzer",
    "Setter": "English Setter",
    "Shiba Inu": "Shiba Inu",
    "Shih Tzu": "Shih Tzu",
    "Sloughi": "Sloughi",
    "Spitz": "German Spitz",
    "Terrier": "Other",
    "Weimaraner": "Weimaraner",
    "Whippet": "Whippet",

    # --- Resolved Splitting Errors & Edge Fallbacks ---
    "American Blue Heeler": "Australian Cattle Dog",
    "Appenzell Mountain Dog": "Appenzeller Sennenhund",
    "Brasileiro, Fila": "Other",
    "Cattle Dog": "Australian Cattle Dog",
    "Hound": "Other",
    "Husky": "Siberian Husky",
    "Klee Kai": "Alaskan Klee Kai",
    "Mountain Dog": "Greater Swiss Mountain Dog",
    "Nureongi": "Other",
    "Queensland Heeler": "Australian Cattle Dog",
    "Sheep Dog": "Other",
    "Shepherd": "German Shepherd Dog",
    "Spaniel": "Cocker Spaniel",

    # --- Mixed / Unknown Defaults ---
    "Mixed Breed (Large)": "Other",
    "Mixed Breed (Medium)": "Other",
    "Mixed Breed (Small)": "Other",
    "Unknown": "Other",

    # --- Inverted/Modified Bulldogs ---
    "Bulldog, American": "American Bulldog",
    "Bulldog, English": "English Bulldog",
    "Bulldog, French": "French Bulldog",
    "Bulldog, Old English": "Olde English Bulldogge",
    "Bulldog, Victorian": "English Bulldog",

    # --- Inverted Mastiffs & Canarios ---
    "Canario, Presa": "Perro de Presa Canario",
    "Mastiff, Bullmastiff": "Bullmastiff",
    "Mastiff, Cane Corso": "Cane Corso",
    "Mastiff, Neapolitan": "Neapolitan Mastiff",
    "Mastiff, Tibetan": "Tibetan Mastiff",

    # --- Inverted Cattle Dogs & Chihuahuas ---
    "Cattle Dog, Australian (Blue Heeler)": "Australian Cattle Dog",
    "Cattle Dog, Australian (Red Heeler)": "Australian Cattle Dog",
    "Chihuahua, Long Coat": "Chihuahua",
    "Chihuahua, Short Coat": "Chihuahua",
    "Chinese Crested Dog": "Chinese Crested",

    # --- Inverted Collies & Coonhounds ---
    "Collie, Bearded": "Bearded Collie",
    "Collie, Border": "Border Collie",
    "Collie, Rough": "Collie",
    "Collie, Smooth": "Collie",
    "Coonhound, Bluetick": "Bluetick Coonhound",
    "Coonhound, English": "American English Coonhound",
    "Coonhound, Redbone": "Redbone Coonhound",
    "Coonhound, Treeing Walker": "Treeing Walker Coonhound",

    # --- Inverted Corgis & Dachshunds ---
    "Corgi, Cardigan Welsh": "Cardigan Welsh Corgi",
    "Corgi, Pembroke Welsh": "Pembroke Welsh Corgi",
    "Dachshund, Miniature Long Haired": "Dachshund",
    "Dachshund, Miniature Smooth Haired": "Dachshund",
    "Dachshund, Miniature Wire Haired": "Dachshund",
    "Dachshund, Standard Long Haired": "Dachshund",
    "Dachshund, Standard Smooth Haired": "Dachshund",
    "Dachshund, Standard Wire Haired": "Dachshund",

    # --- Inverted Elkhounds, Eskimos & Foxhounds ---
    "Elkhound, Norwegian": "Norwegian Elkhound",
    "Eskimo, American": "American Eskimo Dog",
    "Flanders, Bouvier Des": "Bouvier des Flandres",
    "Foxhound, American": "American Foxhound",
    "Foxhound, English": "English Foxhound",

    # --- Inverted Greyhounds, Hounds, & Griffons ---
    "Greyhound, Italian": "Italian Greyhound",
    "Griffon, Brussels": "Brussels Griffon",
    "Griffon, Petit Basset Vendeen": "Petit Basset Griffon Vendéen",
    "Griffon, Wire-Haired Pointing": "Wirehaired Pointing Griffon",
    "Hound, Afghan": "Afghan Hound",
    "Hound, Basset": "Basset Hound",
    "Hound, Black and Tan Coonhound": "Black and Tan Coonhound",
    "Hound, Bloodhound": "Bloodhound",
    "Hound, Halden (Haldenstover)": "Halden Hound",
    "Hound, Ibizan": "Ibizan Hound",
    "Hound, Irish Wolfhound": "Irish Wolfhound",
    "Hound, Pharaoh": "Pharaoh Hound",
    "Hound, Plott": "Plott Hound",
    "Hound, Scottish Deerhound": "Scottish Deerhound",

    # --- Inverted Huskies, Kelpies, & Lapphunds ---
    "Husky, Alaskan": "Alaskan Husky",
    "Husky, Siberian": "Siberian Husky",
    "Kelpie, Australian": "Australian Kelpie",
    "Korean Jindo": "Jindo",
    "Lapphund, Finnish": "Finnish Lapphund",
    "Lundehund, Norwegian": "Norwegian Lundehund",
    "Malamute, Alaskan": "Alaskan Malamute",
    "Malinois, Belgian": "Belgian Malinois",

    # --- Inverted Poodles & Peis ---
    "Buhund, Norwegian": "Norwegian Buhund",
    "Pei, Shar": "Chinese Shar-Pei",
    "Pinscher, Austrian": "Austrian Pinscher",
    "Pinscher, Doberman": "Doberman Pinscher",
    "Pinscher, German": "German Pinscher",
    "Pinscher, Miniature": "Miniature Pinscher",
    "Pointer, English": "English Pointer",
    "Pointer, German Shorthaired": "German Shorthaired Pointer",
    "Pointer, German Wirehaired": "German Wirehaired Pointer",
    "Poodle, Miniature": "Miniature Poodle",
    "Poodle, Standard": "Poodle",
    "Poodle, Toy": "Toy Poodle",
    "Portugese Water Dog": "Portuguese Water Dog",  # Resolves typo path
    "Pyrenees, Great": "Great Pyrenees",

    # --- Inverted Retrievers & Ridgebacks ---
    "Retriever, Black Labrador": "Labrador Retriever",
    "Retriever, Chesapeake Bay": "Chesapeake Bay Retriever",
    "Retriever, Chocolate Labrador": "Labrador Retriever",
    "Retriever, Curly-Coated": "Curly-Coated Retriever",
    "Retriever, Flat-Coated": "Flat-Coated Retriever",
    "Retriever, Golden": "Golden Retriever",
    "Retriever, Labrador": "Labrador Retriever",
    "Retriever, Nova Scotia Duck-Tolling": "Nova Scotia Duck Tolling Retriever",
    "Retriever, Yellow Labrador": "Labrador Retriever",
    "Ridgeback, Rhodesian": "Rhodesian Ridgeback",
    "Ridgeback, Thai": "Thai Ridgeback",

    # --- Inverted Schnauzers & Setters ---
    "Schnauzer, Giant": "Giant Schnauzer",
    "Schnauzer, Miniature": "Miniature Schnauzer",
    "Schnauzer, Standard": "Standard Schnauzer",
    "Setter, English": "English Setter",
    "Setter, Gordon": "Gordon Setter",
    "Setter, Irish": "Irish Setter",

    # --- Inverted Sheepdogs & Shepherds ---
    "Sheepdog, Caucasian Ovtcharka": "Caucasian Shepherd Dog",
    "Sheepdog, Mcnab": "McNab",
    "Sheepdog, Old English": "Old English Sheepdog",
    "Sheepdog, Polish Lowland": "Polish Lowland Sheepdog",
    "Sheepdog, Shetland": "Shetland Sheepdog",
    "Shepherd, Anatolian": "Anatolian Shepherd Dog",
    "Shepherd, Australian": "Australian Shepherd",
    "Shepherd, Belgian Malinois": "Belgian Malinois",
    "Shepherd, Belgian Sheepdog": "Belgian Sheepdog",
    "Shepherd, Belgian Tervuren": "Belgian Tervuren",
    "Shepherd, Dutch": "Dutch Shepherd",
    "Shepherd, English": "English Shepherd",
    "Shepherd, German": "German Shepherd Dog",
    "Shepherd, German King": "Shiloh Shepherd dog",
    "Shepherd, White German": "White German Shepherd",

    # --- Inverted Spans, Spitzes, & Terriers ---
    "Spaniel, American Cocker": "Cocker Spaniel",
    "Spaniel, American Water": "American Water Spaniel",
    "Spaniel, Brittany": "Brittany",
    "Spaniel, Cavalier King Charles": "Cavalier King Charles Spaniel",
    "Spaniel, Clumber": "Clumber Spaniel",
    "Spaniel, Cocker": "Cocker Spaniel",
    "Spaniel, English Cocker": "English Cocker Spaniel",
    "Spaniel, English Springer": "English Springer Spaniel",
    "Spaniel, English Toy": "English Toy Spaniel",
    "Spaniel, Irish Water": "Irish Water Spaniel",
    "Spaniel, Sussex": "Sussex Spaniel",
    "Spaniel, Tibetan": "Tibetan Spaniel",
    "Spaniel, Welsh Springer": "Welsh Springer Spaniel",
    "Spinone, Italian": "Spinone Italiano",
    "Spitz, Finnish": "Finnish Spitz",
    "Spitz, German": "German Spitz",
    "Taiwanese Mountain Dog": "Taiwan Dog",

    # --- Extensive Inverted Terrier Array Matrix ---
    "Terrier, Airedale": "Airedale Terrier",
    "Terrier, American Hairless": "American Hairless Terrier",
    "Terrier, American Pit Bull": "American Pit Bull Terrier",
    "Terrier, American Staffordshire": "American Staffordshire Terrier",
    "Terrier, Australian": "Australian Terrier",
    "Terrier, Bedlington": "Bedlington Terrier",
    "Terrier, Black Russian": "Black Russian Terrier",
    "Terrier, Border": "Border Terrier",
    "Terrier, Boston": "Boston Terrier",
    "Terrier, Bull": "Bull Terrier",
    "Terrier, Cairn": "Cairn Terrier",
    "Terrier, Dandi Dinmont": "Dandie Dinmont Terrier",
    "Terrier, Fox": "Wire Fox Terrier",
    "Terrier, Fox, Smooth": "Smooth Fox Terrier",
    "Terrier, Glen of Imaal": "Glen of Imaal Terrier",
    "Terrier, Irish": "Irish Terrier",
    "Terrier, Jack Russell": "Jack Russell Terrier",
    "Terrier, Kerry Blue": "Kerry Blue Terrier",
    "Terrier, Lakeland": "Lakeland Terrier",
    "Terrier, Manchester": "Manchester Terrier",
    "Terrier, Norfolk": "Norfolk Terrier",
    "Terrier, Norwich": "Norwich Terrier",
    "Terrier, Parson Jack Russell": "Parson Russell Terrier",
    "Terrier, Patterdale (Fell)": "Patterdale Terrier",
    "Terrier, Pit Bull": "Pit Bull",
    "Terrier, Rat": "Rat Terrier",
    "Terrier, Scottish Scottie": "Scottish Terrier",
    "Terrier, Sealyham": "Sealyham Terrier",
    "Terrier, Silky": "Silky Terrier",
    "Terrier, Skye": "Skye Terrier",
    "Terrier, Smooth Fox": "Smooth Fox Terrier",
    "Terrier, Soft Coated Wheaten": "Soft Coated Wheaten Terrier",
    "Terrier, Staffordshire Bull": "Staffordshire Bull Terrier",
    "Terrier, Tibetan": "Tibetan Terrier",
    "Terrier, Toy Fox": "Toy Fox Terrier",
    "Terrier, Welsh": "Welsh Terrier",
    "Terrier, West Highland White Westie": "West Highland White Terrier",
    "Terrier, Wheaten": "Soft Coated Wheaten Terrier",
    "Terrier, Wire Fox": "Wire Fox Terrier",
    "Terrier, Wirehaired": "Wire Fox Terrier",
    "Terrier, Yorkshire, Yorkie": "Yorkshire Terrier",
    "Vallhund, Swedish": "Swedish Vallhund",
    "Vizsla, Smooth Haired": "Vizsla",
    "Water Dog, Portuguese": "Portuguese Water Dog",
    "Wolfhound, Irish": "Irish Wolfhound",
    "Xoloitzcuintle (Mexican Hairless)": "Xoloitzcuintle",
}

def translate_breed(shelterluv_breed_string):
    """
    Cleans up string variables and runs cross-reference translation mappings.
    Returns standard 'Other' fallback if match isn't verified.
    """
    if not shelterluv_breed_string:
        return "Other"
    
    cleaned = str(shelterluv_breed_string).strip()
    return BREED_MAP.get(cleaned, "Other")